# Generated by Django 4.2.23 on 2025-06-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_add_child_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnfood',
            name='food_category',
            field=models.ForeignKey(blank=True, help_text='Food category', null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.cnfoodcategory'),
        ),
    ]
